artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://storage.googleapis.com/heispv/pizza-steak-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/pizza_steak_data


base_model_preparation:
  root_dir: artifacts/base_model_preparation
  base_model_path: artifacts/base_model_preparation/base_model.h5
  updated_base_model_path: artifacts/base_model_preparation/updated_base_model.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_log_dir: artifacts/prepare_callbacks/tensorboard_logs
  checkpoint_dir: artifacts/prepare_callbacks/checkpoint_dir/

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/trained_model.h5
  result_image_path: artifacts/model_training/training_history.png
  evaluation_pictures: artifacts/model_training/evaluation_pictures.png
